# Generated by Django 2.0.6 on 2018-07-10 03:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('cash', models.IntegerField()),
                ('details', models.CharField(max_length=10000)),
                ('cashier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Account')),
            ],
        ),
        migrations.CreateModel(
            name='Dishes',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('price', models.IntegerField()),
                ('code', models.CharField(max_length=10)),
            ],
        ),
    ]
